__author__ = "Feng Gu"
__email__ = "contact@fenggu.me"

"""
   isort:skip_file
"""

import ast
import os
import re

LAYOUT = "env"

pattern = re.compile(r"(?<!^)(?=[A-Z])")

env_path = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
    "shimmy",
)

files = (file for file in os.listdir(env_path) if 
    os.path.isfile(os.path.join(env_path, file)) 
    and '__init__' not in file 
    and 'registration' not in file)

for item in files:
    file = os.path.join(env_path, item)
    file_name = item.split(".")[0]

    # getting docstring
    file_contents = ""
    with open(file) as fd:
        file_contents = fd.read()
    module = ast.parse(file_contents)
    docstring = ast.get_docstring(module)
    if docstring is None:
        docstring = ""

    # output path
    output_path = os.path.join(
        os.path.dirname(os.path.dirname(__file__)),
        'contents',
        f"{file_name}.md",
    )

    front_matter = f"""---
autogenerated:
title: {file_name}
---
"""
    title = f"# {file_name}"

    if docstring is None or docstring == "":
        docstring = "No information provided"
    all_text = f"""{front_matter}

{docstring}
"""
    file = open(output_path, "w+", encoding="utf-8")
    file.write(all_text)
    file.close()