name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v6
      - run: |
           docker build -f bin/all.Dockerfile \
             --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
             --tag shimmy-docker .
      - name: Run tests
        run: docker run shimmy-docker pytest
