name: build
on: [pull_request, push]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  optional-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
           docker build -f py.Dockerfile \
             --build-arg PYTHON_VERSION="3.10" \
             --tag shimmy-docker .

        # only install atari and run the pytest atari tests then uninstall atari
      - name: Run atari tests
        run: |
          docker run shimmy-docker pip install .[atari] --no-cache-dir
          docker run shimmy-docker pytest tests/test_atari.py
          docker run shimmy-docker pip uninstall --yes ale-py

        # Repeat for dm-control
      - name: Run dm-control tests
        run: |
          docker run shimmy-docker pip install .[dm-control] --no-cache-dir
          docker run shimmy-docker pytest tests/test_dm_control.py 
          docker run shimmy-docker pip uninstall --yes dm_control

        # Repeat for openspiel
      - name: Run openspiel tests
        run: | 
          docker run shimmy-docker pip install .[openspiel] --no-cache-dir 
          docker run shimmy-docker pytest tests/test_openspiel.py 
          docker run shimmy-docker pip uninstall --yes openspiel
