name: build
on: [pull_request, push]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  optional-test-atari:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Atari
      - run: |
           docker build -f bin/atari.Dockerfile \
             --build-arg PYTHON_VERSION='3.10' \
             --tag shimmy-atari-docker .
      - name: Run atari tests
        run: docker run shimmy-atari-docker pytest tests/test_atari.py
