name: build
on: [pull_request, push]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  optional-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # dm-lab
      - run: |
          docker build -f bin/dm_lab.Dockerfile \
            --build-arg PYTHON_VERSION='3.10' \
            --tag shimmy-dm_lab-docker .
      - name: Run dm-lab tests
        run: docker run shimmy-dm_lab-docker pytest tests/test_dm_lab.py

        # dm-control-multi-agent
      - run: |
          docker build -f bin/dm_control_multiagent.Dockerfile \
            --build-arg PYTHON_VERSION='3.10' \
            --tag shimmy-dm-control-multi-agent-docker .
      - name: Run dm-control-multi-agent tests
        run: docker run shimmy-dm-control-multi-agent-docker pytest tests/test_dm_control_multi_agent.py

        # bsuite
      - run: |
          docker build -f bin/bsuite.Dockerfile \
            --build-arg PYTHON_VERSION='3.10' \
            --tag shimmy-bsuite-docker .
      - name: Run bsuite tests
        run: docker run shimmy-bsuite-docker pytest tests/test_bsuite.py


        # Atari
      - run: |
           docker build -f bin/atari.Dockerfile \
             --build-arg PYTHON_VERSION='3.10' \
             --tag shimmy-atari-docker .
      - name: Run atari tests
        run: docker run shimmy-atari-docker pytest tests/test_atari.py

        # dm-control
      - run: |
          docker build -f bin/dm_control.Dockerfile \
            --build-arg PYTHON_VERSION='3.10' \
            --tag shimmy-dm-control-docker .
      - name: Run dm-control tests
        run: docker run shimmy-dm-control-docker pytest tests/test_dm_control.py

        # openspiel
      - run: |
          docker build -f bin/openspiel.Dockerfile \
            --build-arg PYTHON_VERSION='3.10' \
            --tag shimmy-openspiel-docker .
      - name: Run openspiel tests
        run: docker run shimmy-openspiel-docker pytest tests/test_openspiel.py

        # meltingpot
      - run: |
          docker build -f bin/meltingpot.Dockerfile \
            --build-arg PYTHON_VERSION='3.19' \
            --tag shimmy-meltingpot-docker .
      - name: Run meltingpot tests
        run: docker run shimmy-meltingpot-docker pytest tests/test_meltingpot.py

