name: build
on: [pull_request, push]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  optional-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # melting pot
      - if: ${{ steps.cache-melting-pot-docker.outputs.cache-hit == 'true' }}
        name: Load melting pot Docker image (if it has been archived)
        run: docker load --input bin/melting_pot_docker_image.tar
      - if: ${{ steps.cache-melting-pot-docker.outputs.cache-hit == 'false' }}
        name: Build melting pot from Dockerfile
        run: |
          docker build -f bin/melting_pot.Dockerfile \
            --build-arg PYTHON_VERSION='3.9' \
            --tag shimmy-melting-pot-docker .
      - name: Export docker melting pot image
        run docker export shimmy-melting-pot-docker > bin/melting_pot_docker_image.tar
      - name: Cache melting pot Docker image
        id: cache-melting-pot-docker
        uses: actions/cache@v3
        env:
          cache-name: cache-melting-pot-docker
        with:
          path: bin/melting_pot_docker_image.tar
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('bin/melting_pot_docker_image.tar') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Run melting pot tests
        run: docker run shimmy-melting-pot-docker pytest tests/test_melting_pot.py

        # Atari
      - run: |
           docker build -f bin/atari.Dockerfile \
             --build-arg PYTHON_VERSION='3.10' \
             --tag shimmy-atari-docker .
      - name: Run atari tests
        run: docker run shimmy-atari-docker pytest tests/test_atari.py

        # dm-control
      - run: |
          docker build -f bin/dm_control.Dockerfile \
            --build-arg PYTHON_VERSION='3.10' \
            --tag shimmy-dm-control-docker .
      - name: Run dm-control tests
        run: docker run shimmy-dm-control-docker pytest tests/test_dm_control.py

        # dm-control multi-agent
      - run: |
          docker build -f bin/dm_control_multi_agent.Dockerfile \
            --build-arg PYTHON_VERSION='3.10' \
            --tag shimmy-dm-control-multi-agent-docker .
      - name: Run dm-control multi-agent tests
        run: docker run shimmy-dm-control-multi-agent-docker pytest tests/test_dm_control_multi_agent.py

        # openspiel
      - run: |
          docker build -f bin/openspiel.Dockerfile \
            --build-arg PYTHON_VERSION='3.10' \
            --tag shimmy-openspiel-docker .
      - name: Run openspiel tests
        run: docker run shimmy-openspiel-docker pytest tests/test_openspiel.py

        # TODO: add dm lab and bsuite (?)
