name: build
on: [pull_request, push]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  optional-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        # melting pot
      - run: |
          docker build -f bin/meltin_gpot.Dockerfile \
            --build-arg PYTHON_VERSION='3.9' \
            --tag shimmy-melting-pot-docker .
      - name: Run melting pot tests
        run: docker run shimmy-melting-pot-docker pytest tests/test_melting_pot.py

        # Atari
      - run: |
           docker build -f bin/atari.Dockerfile \
             --build-arg PYTHON_VERSION='3.10' \
             --tag shimmy-atari-docker .
      - name: Run atari tests
        run: docker run shimmy-atari-docker pytest tests/test_atari.py

        # dm-control
      - run: |
          docker build -f bin/dm_control.Dockerfile \
            --build-arg PYTHON_VERSION='3.10' \
            --tag shimmy-dm-control-docker .
      - name: Run dm-control tests
        run: docker run shimmy-dm-control-docker pytest tests/test_dm_control.py

        # dm-control multi-agent
      - run: |
          docker build -f bin/dm_control_multi_agent.Dockerfile \
            --build-arg PYTHON_VERSION='3.10' \
            --tag shimmy-dm-control-multi-agent-docker .
      - name: Run dm-control multi-agent tests
        run: docker run shimmy-dm-control-multi-agent-docker pytest tests/test_dm_control_multi_agent.py

        # openspiel
      - run: |
          docker build -f bin/openspiel.Dockerfile \
            --build-arg PYTHON_VERSION='3.10' \
            --tag shimmy-openspiel-docker .
      - name: Run openspiel tests
        run: docker run shimmy-openspiel-docker pytest tests/test_openspiel.py

        # TODO: add dm lab and bsuite (?)
