name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  optional-test-dm-control:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.14']
    steps:
      - uses: actions/checkout@v6

      # DM Control
      - run: |
          docker build -f bin/dm_control.Dockerfile \
            --build-arg PYTHON_VERSION='${{ matrix.python-version }}' \
            --tag shimmy-dm-control-docker .
      - name: Run dm-control tests
        run: docker run shimmy-dm-control-docker pytest tests/test_dm_control.py

  optional-test-dm-control-multiagent:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.14']
    steps:
      - uses: actions/checkout@v6

      # DM Control Multi-Agent
      - run: |
          docker build -f bin/dm_control_multiagent.Dockerfile \
            --build-arg PYTHON_VERSION='${{ matrix.python-version }}' \
            --tag shimmy-dm-control-multi-agent-docker .
      - name: Run dm-control-multi-agent tests
        run: docker run shimmy-dm-control-multi-agent-docker pytest tests/test_dm_control_multi_agent.py

  optional-test-openspiel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.14']
    steps:
      - uses: actions/checkout@v6

      # OpenSpiel
      - run: |
          docker build -f bin/openspiel.Dockerfile \
            --build-arg PYTHON_VERSION='${{ matrix.python-version }}' \
            --tag shimmy-openspiel-docker .
      - name: Run openspiel tests
        run: docker run shimmy-openspiel-docker pytest tests/test_openspiel.py

  optional-test-gym-v21:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v6

      # Gym v21
      - run: |
          docker build -f bin/gym-v21.Dockerfile \
            --build-arg PYTHON_VERSION='${{ matrix.python-version }}' \
            --tag shimmy-gym-v21-docker .
      - name: Run Gym v0.21 tests
        run: docker run shimmy-gym-v21-docker pytest tests/test_gym.py

  optional-test-gym-v26:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.14']
    steps:
      - uses: actions/checkout@v6

      # Gym v26
      - run: |
          docker build -f bin/gym-v26.Dockerfile \
            --build-arg PYTHON_VERSION='${{ matrix.python-version }}' \
            --tag shimmy-gym-v26-docker .
      - name: Run Gym v0.26 tests
        run: docker run shimmy-gym-v26-docker pytest tests/test_gym.py

  optional-test-android-env:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.12']
    steps:
      - uses: actions/checkout@v6

      # AndroidEnv
      - run: |
          docker build -f bin/android_env.Dockerfile \
            --build-arg PYTHON_VERSION='${{ matrix.python-version }}' \
            --tag shimmy-android-env-docker .
      - name: Run android_env tests
        run: docker run shimmy-android-env-docker pytest tests/test_android_env.py
